version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    environment:
      - DATABASE_URL=mysql://root:password@db/
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
    command: tail -f /dev/null
    ports: 
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db-data: